all:
	g++ mainUDPClient.cpp UDP.cpp UDPClient.cpp udpTcpParent.cpp -lm -ansi -pedantic -lpthread -Wno-write-strings -o UDPclient.out

	g++ mainTCPClient.cpp TCP.cpp TCPClient.cpp udpTcpParent.cpp -lm -ansi -pedantic -lpthread -Wno-write-strings -o TCPClient.out
